/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.io.File;
import java.io.IOException;
import java.util.concurrent.TimeUnit;

import org.junit.Test;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

import com.google.common.io.Files;

public class SeleniumTest {

    @Test
    public void testSelenium() {
        // ドライバを生成
        WebDriver driver = new FirefoxDriver();
        // タイムアウトを設定
        driver.manage().timeouts().implicitlyWait(15, TimeUnit.SECONDS);
        // ウインドウを最大化
        driver.manage().window().maximize();
        // 画面遷移
        driver.get("http://www.yahoo.co.jp");
        // yahooのスクリーンショットを/tmpに保存
        File srcFile = ((TakesScreenshot) driver).getScreenshotAs(OutputType.FILE);
        File destFile = new File("F:\\trash\\test.png");
        try {
            Files.move(srcFile, destFile);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        // ドライバを終了
        driver.quit();
    }
}
