/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.io.File;
import java.io.IOException;
import java.util.concurrent.TimeUnit;

import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebDriverException;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.ExpectedCondition;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import com.google.common.io.Files;

public class SeleniumTest {

    @Test
    public void testSelenium() {
        // ドライバを生成
        WebDriver driver = new FirefoxDriver();
        // タイムアウトを設定
        driver.manage().timeouts().implicitlyWait(15, TimeUnit.SECONDS);
        // ウインドウを最大化
        driver.manage().window().maximize();
        // 画面遷移
        driver.get("https://www.hatena.ne.jp/login");
        WebElement user = driver.findElement(By.id("login-name"));
        user.sendKeys("nagase2.mobile@gmail.com");
        
        WebElement pass = driver.findElement(By.className("password"));
        pass.sendKeys("nagase222");
        
        WebElement btn = driver.findElement(By.className("submit-button"));
        btn.click();
        
        //proile
        WebDriverWait wait = new WebDriverWait(driver, 30);
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.className("profile-image")));
        
        // yahooのスクリーンショットを/tmpに保存
        File srcFile = ((TakesScreenshot) driver).getScreenshotAs(OutputType.FILE);
        File destFile = new File("./testresult/firefoxtest.png");
        try {
            Files.move(srcFile, destFile);
        } catch (IOException e) {                                                                                                                                                                                                                                                                                                
            throw new RuntimeException(e);
        }
        // ドライバを終了
        driver.quit();
    }
}
